### ISSUE TITLE
Traceback on indent_dm

### ISSUE THREAD

**Issue by fsundermeyer** [openSUSE/docmanager#11]
$ docmanager -s maintainer=fs -f xml/depl_*.xml
Traceback (most recent call last):
  File "/usr/bin/docmanager", line 9, in <module>
    load_entry_point('docmanager==3.0.0-beta1', 'console_scripts', 'docmanager')()
  File "/usr/lib/python3.4/site-packages/docmanager/**init**.py", line 126, in main
    DocManager()
  File "/usr/lib/python3.4/site-packages/docmanager/**init**.py", line 37, in **init**
    action.Actions(parser.files, parser.action, parser.arguments)
  File "/usr/lib/python3.4/site-packages/docmanager/action.py", line 40, in **init**
    self.**files = filehandler.Files(files)
  File "/usr/lib/python3.4/site-packages/docmanager/filehandler.py", line 51, in __init**
    self.**xml_handlers.append(xmlhandler.XmlHandler(file))
  File "/usr/lib/python3.4/site-packages/docmanager/xmlhandler.py", line 42, in __init**
    self.create_group()
  File "/usr/lib/python3.4/site-packages/docmanager/xmlhandler.py", line 54, in create_group
    self.write()
  File "/usr/lib/python3.4/site-packages/docmanager/xmlhandler.py", line 159, in write
    self.indent_dm()
  File "/usr/lib/python3.4/site-packages/docmanager/xmlhandler.py", line 144, in indent_dm
    infoindent = "".join(info.tail.split('\n'))
AttributeError: 'NoneType' object has no attribute 'tail'

**Comment by tomschr** [comment]
Related to issue #10.

**Comment by tomschr** [comment]
I think, we can close this. Already fixed.
