### ISSUE TITLE
docmanager set --priority 1,2 xml/FILE.xml causes traceback

### ISSUE THREAD

**Issue by taroth21** [openSUSE/docmanager#48]
Traceback (most recent call last):
  File "/usr/bin/docmanager", line 9, in <module>
    load_entry_point('docmanager==3.0.0', 'console_scripts', 'docmanager')()
  File "/usr/lib/python3.4/site-packages/docmanager/**init**.py", line 295, in main
    action.Actions(parsecli(cliargs))
  File "/usr/lib/python3.4/site-packages/docmanager/**init**.py", line 222, in parsecli
    input_format_check(args)
  File "/usr/lib/python3.4/site-packages/docmanager/**init**.py", line 274, in input_format_check
    args.priority = int(args.priority)
ValueError: invalid literal for int() with base 10: '1,2'

**Comment by mschnitzer** [comment]
Just as a notice for me:

```
docmanager set --priority 1,2 xml/authors.xml
```
